export const MENUITEMS = [
  {
    menutitle: "MAIN",
    Items: [
      { path: `/dashboard`, icon: "fe fe-home", type: "link", active: false, selected: false, title: "Dashboard" },
    ],
  },
  {
    menutitle: "UI KIT",
    Items: [
      {
        path: `/users`,
        icon: "fe fe-users",
        type: "link",
        active: true,
        selected: false,
        title: "Users",
      },
      {
      path: `/profile`,
      icon: "fe fe-users",
      type: "link",
      active: true,
      selected: false,
      title: "Profile",
    },  {
      path: `/wallet`,
      icon: "fe fe-users",
      type: "link",
      active: true,
      selected: false,
      title: "Wallet",
    },{
      path: `/movies`,
      icon: "fe fe-users",
      type: "link",
      active: true,
      selected: false,
      title: "Movies",
    },
      
    ],
  },
  {
    menutitle: "MISC PAGES",
    Items: [
      {
        title: "Authentication",
        icon: "fe fe-users",
        type: "sub",
        Name: "",
        Names: "",
        active: false,
        selected: false,
        children: [
          { path: `/authentication/login`, type: "link", active: false, selected: false, title: "Login" },
          { path: `/authentication/register`, type: "link", active: false, selected: false, title: "Register" },
          {
            path: `/authentication/forgotpassword`,
            type: "link",
            active: false,
            selected: false,
            title: "Forgot Password",
          },
          { path: `/authentication/lockscreen`, type: "link", active: false, selected: false, title: "LockScreen" },
          {
            title: "ErrorPage",
            icon: "ti-face-smile",
            type: "sub",
            Name: "",
            Names: "",
            active: false,
            selected: false,
            children: [
              {
                path: `/authentication/errorpage/error400`,
                type: "link",
                active: false,
                selected: false,
                title: "Error400",
              },
              {
                path: `/authentication/errorpage/error401`,
                type: "link",
                active: false,
                selected: false,
                title: "Error401",
              },
              {
                path: `/authentication/errorpage/error403`,
                type: "link",
                active: false,
                selected: false,
                title: "Error403",
              },
              {
                path: `/authentication/errorpage/error404`,
                type: "link",
                active: false,
                selected: false,
                title: "Error404",
              },
              {
                path: `/authentication/errorpage/error500`,
                type: "link",
                active: false,
                selected: false,
                title: "Error500",
              },
              {
                path: `/authentication/errorpage/error503`,
                type: "link",
                active: false,
                selected: false,
                title: "Error503",
              },
            ],
          },
        ],
      },
    ],
  },

  {
    menutitle: "GENERAL",
    Items: [
      {
        title: "Maps",
        icon: "fe fe-map-pin",
        type: "sub",
        Name: "",
        Names: "",
        children: [
          { path: `/maps/leafletmaps`, type: "link", active: false, selected: false, title: "Leaflet-Maps" },
          { path: `/maps/simplemaps`, type: "link", active: false, selected: false, title: "Simple-Maps" },
        ],
      },
      {
        title: "Charts",
        icon: "fe fe-bar-chart-2",
        type: "sub",
        Name: "",
        Names: "",
        badge: "badge bg-secondary side-badge",
        badgetxt: "6",
        children: [
          { path: `/charts/chartjs`, type: "link", active: false, selected: false, title: " Chartjs" },
          {
            path: `/charts/echart`,
            type: "sub",
            Name: "",
            Names: "",
            title: " Echart",
            children: [
              { path: `/charts/echart/lines`, type: "link", active: false, selected: false, title: " Line Chart" },
              { path: `/charts/echart/bar`, type: "link", active: false, selected: false, title: " Bar Chart" },
              {
                path: `/charts/echart/candlestick`,
                type: "link",
                active: false,
                selected: false,
                title: " Candle Stick Chart",
              },

              { path: `/charts/echart/scatter`, type: "link", active: false, selected: false, title: " Scatter Chart" },
              { path: `/charts/echart/tree`, type: "link", active: false, selected: false, title: " Tree Chart" },
            ],
          },

          {
            path: `/charts/apexchart`,
            type: "sub",
            Name: "",
            Names: "",
            title: " ApexChart",
            children: [
              { path: `/charts/apexchart/line`, type: "link", active: false, selected: false, title: " Line Chart" },
              { path: `/charts/apexchart/area`, type: "link", active: false, selected: false, title: " Area Chart" },
              {
                path: `/charts/apexchart/column`,
                type: "link",
                active: false,
                selected: false,
                title: " Column Chart",
              },
              { path: `/charts/apexchart/bar`, type: "link", active: false, selected: false, title: " Bar Chart" },
              { path: `/charts/apexchart/mixed`, type: "link", active: false, selected: false, title: " Mixed Chart" },
              {
                path: `/charts/apexchart/timeline`,
                type: "link",
                active: false,
                selected: false,
                title: " Timeline Chart",
              },
              {
                path: `/charts/apexchart/candlestick`,
                type: "link",
                active: false,
                selected: false,
                title: " CandleStick Chart",
              },
              {
                path: `/charts/apexchart/boxplot`,
                type: "link",
                active: false,
                selected: false,
                title: " Boxplot Chart",
              },
              {
                path: `/charts/apexchart/treemap`,
                type: "link",
                active: false,
                selected: false,
                title: " Treemap Chart",
              },
              { path: `/charts/apexchart/pie`, type: "link", active: false, selected: false, title: " Pie Chart" },
              {
                path: `/charts/apexchart/radialbar`,
                type: "link",
                active: false,
                selected: false,
                title: " Radialbar Chart",
              },
              { path: `/charts/apexchart/radar`, type: "link", active: false, selected: false, title: " Radar Chart" },
              {
                path: `/charts/apexchart/polararea`,
                type: "link",
                active: false,
                selected: false,
                title: " PolarArea Chart",
              },
            ],
          },
        ],
      },
      {
        title: "Icons",
        icon: "fe fe-wind",
        type: "sub",
        Name: "",
        Names: "",
        children: [
          { path: `/icons/bootstrapicons`, type: "link", active: false, selected: false, title: "Bootstrap Icons" },
          { path: `/icons/feathericons`, type: "link", active: false, selected: false, title: " Feather Icons" },
          { path: `/icons/flagicons`, type: "link", active: false, selected: false, title: " Flag Icons" },
          { path: `/icons/fontawesome`, type: "link", active: false, selected: false, title: "Font-Awesome Icons" },
          { path: `/icons/ionicicons`, type: "link", active: false, selected: false, title: " Ionic Icons" },
          {
            path: `/icons/materialdesignicons`,
            type: "link",
            active: false,
            selected: false,
            title: " MaterialDesign Icons",
          },
          { path: `/icons/pe7icons`, type: "link", active: false, selected: false, title: " Pe7 Icons" },
          { path: `/icons/simplelineicons`, type: "link", active: false, selected: false, title: "Simpleline Icons" },
          { path: `/icons/themifyicons`, type: "link", active: false, selected: false, title: " Themify Icons" },
          { path: `/icons/typiconsicons`, type: "link", active: false, selected: false, title: " Typicons Icons" },
          { path: `/icons/weathericons`, type: "link", active: false, selected: false, title: " Weather Icons" },
        ],
      },
    ],
  },
];
